name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.8', '3.9', '3.10' ]
    name: Python ${{ matrix.python-version }} sample
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install the test dependencies
        run: pip install black isort                
      - name: Install current project
        run: python -m pip install .
      - name: Check code format
        run: |
          black --check .
          isort --profile black --check .
      - name: Check tool version
        run: readactor --version

      # - name: Run Old Tests
      #   run: python -m test scripts.command_line_tool

#      - name: Run Click Test of Version
#        run: python  -m unittest -v tests.test_click

      - name: Run New Tests
        run: python -m unittest discover -v

# see https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
          cache: 'pip'
      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/
          .
      - name: Publish test 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        if: github.ref != 'refs/heads/master'
        with:
          password: ${{ secrets.TESTPYPI_API_TOKEN_FOR_READCHINALOOKUP }}
          repository_url: https://test.pypi.org/legacy/
          skip_existing: true

  # Note(QG): this section should be replaced with git action of python semantic release
  # TODO: release precedure needs documentation
      - name: Publish distribution 📦 to PyPI
        if: github.ref == 'refs/heads/master'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API }}
